class MockChatProvider {
    multiSession = true;
    delayMs;
    sessions = [];
    messagesBySession = {};
    responseGenerator;
    constructor(options) {
        this.delayMs = options?.delayMs ?? 400;
        this.responseGenerator =
            options?.responseGenerator ??
                ((msg) => {
                    if (/hello|hi|hey/i.test(msg)) {
                        return "Hello! How can I assist you with TechOrion AI services today?";
                    }
                    if (/pricing|cost/i.test(msg)) {
                        return "Our plans start with flexible tiers suited for teams of any scale. Would you like to view our pricing breakdown?";
                    }
                    if (/support|help/i.test(msg)) {
                        return "I'm here to help! You can ask questions, explore our documentation, or test our widget capabilities.";
                    }
                    return `I received your message: "${msg}". This response is generated by MockChatProvider for local testing and demonstration.`;
                });
        // Initialize with a default session
        const defaultSessionId = "mock-session-1";
        const now = new Date().toISOString();
        this.sessions.push({
            id: defaultSessionId,
            title: options?.initialSessionTitle || "Welcome Chat",
            createdAt: now,
        });
        this.messagesBySession[defaultSessionId] = [
            {
                role: "assistant",
                content: "Welcome to TechOrion AI! This chat session is powered by `MockChatProvider` for offline and local testing.",
                createdAt: now,
            },
        ];
    }
    async listSessions(options) {
        return [...this.sessions];
    }
    async createSession() {
        const newId = `mock-session-${Date.now()}`;
        const now = new Date().toISOString();
        const newSession = {
            id: newId,
            title: `Chat ${this.sessions.length + 1}`,
            createdAt: now,
        };
        this.sessions.unshift(newSession);
        this.messagesBySession[newId] = [
            {
                role: "assistant",
                content: "New chat session started. How can I help you?",
                createdAt: now,
            },
        ];
        return newId;
    }
    async listSessionMessages(options) {
        const sessionId = options.sessionId || "mock-session-1";
        return this.messagesBySession[sessionId] || [];
    }
    async sendMessage(options) {
        let sessionId = options.sessionId;
        if (!sessionId ||
            sessionId === "new" ||
            !this.messagesBySession[sessionId]) {
            sessionId = this.sessions[0]?.id || "mock-session-1";
        }
        if (!this.messagesBySession[sessionId]) {
            this.messagesBySession[sessionId] = [];
        }
        const now = new Date().toISOString();
        // Append user message
        this.messagesBySession[sessionId].push({
            role: "user",
            content: options.content,
            createdAt: now,
        });
        // Simulate async network latency
        if (this.delayMs > 0) {
            await new Promise((resolve) => setTimeout(resolve, this.delayMs));
        }
        const replyContent = this.responseGenerator(options.content);
        const reply = {
            role: "assistant",
            content: replyContent,
            createdAt: new Date().toISOString(),
        };
        this.messagesBySession[sessionId].push(reply);
        return reply;
    }
}
export default MockChatProvider;
if (typeof window !== "undefined") {
    window.MockChatProvider = MockChatProvider;
}
